sudo: required

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

services: docker

env:
  matrix:
  - INSTANCE=cron-ubuntu-1204
  - INSTANCE=cron-ubuntu-1404
  - INSTANCE=cron-centos-6
  - INSTANCE=cron-centos-7
  - INSTANCE=config-ubuntu-1204
  - INSTANCE=config-ubuntu-1404
  - INSTANCE=config-centos-6
  - INSTANCE=config-centos-7
  - INSTANCE=delete_validation-ubuntu-1204
  - INSTANCE=delete_validation-ubuntu-1404
  - INSTANCE=delete_validation-centos-6
  - INSTANCE=delete_validation-centos-7
  - INSTANCE=service_upstart-ubuntu-1204
  - INSTANCE=service_upstart-ubuntu-1404
  - INSTANCE=service_systemd-centos-7
  - INSTANCE=service_runit-ubuntu-1204
  - INSTANCE=service_runit-ubuntu-1404
  - INSTANCE=service_runit-centos-6
  - INSTANCE=service_runit-centos-7
  - INSTANCE=service_init-ubuntu-1204
  - INSTANCE=service_init-ubuntu-1404
  - INSTANCE=service_init-centos-6

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker
  - /opt/chefdk/embedded/bin/chef gem install rubocop -v 0.37
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
